
console.log('');
console.log('');

console.log(ntw.evaluate_number_with_currency(12300.99));
console.log('');
console.log(ntw.evaluate_number_with_currency(102300.99));
console.log('');
console.log(ntw.evaluate_number_with_currency(1000.99));
console.log('');
console.log(ntw.evaluate_number_with_currency(3000.99));
console.log('');
console.log(ntw.evaluate_number_with_currency(10000.99));
console.log('');
console.log(ntw.evaluate_number_with_currency(100000.99));
console.log('');
console.log(ntw.evaluate_number_with_currency(999999.99));
console.log('');
console.log(ntw.evaluate_number_with_currency(102454.99));
console.log('');
console.log(ntw.evaluate_number_with_currency(384454.99));
console.log('');
/*
console.log(ntw.evaluate_number(210.21));
console.log('');
console.log(ntw.evaluate_number(137.11));
console.log('');
console.log(ntw.evaluate_number(444.11));
console.log('');
console.log(ntw.evaluate_number(808.01));
console.log('');
console.log(ntw.evaluate_number(39.99));
console.log('');
console.log(ntw.evaluate_number(1233300.99));
console.log('');
console.log(ntw.evaluate_number(300101.01));
console.log('');
console.log(ntw.evaluate_number(808.01));
console.log('');
console.log(ntw.evaluate_number(200.01));
console.log('');
console.log(ntw.evaluate_number(101.01));
console.log('');
console.log(ntw.evaluate_number(100.01));
console.log('');
console.log(ntw.evaluate_number(39.09));
console.log('');
 */
